name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_RASCASOFT_USER}}
        password: ${{secrets.DOCKER_RASCASOFT_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/rascasoft/nginx-unprivileged-index:latest
    - name: Push the Docker image
      run: docker push docker.io/rascasoft/nginx-unprivileged-index:latest
